# Generated by Django 3.2.4 on 2021-07-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='/media/pics/mumbai.jpg', upload_to='pics'),
        ),
    ]
